image: gitpod/workspace-node-lts

# Commands that will run on workspace start
tasks:
  - name: Install n8n and dependencies
    init: npm install n8n -g && npm i
    # command: n8n start

# when ready to test the node
# In your node directory
# $ npm run build
# $ npm link
# then $ cd ~/.n8n/nodes/
# $ npm link n8n-nodes-package-name
# $ n8n start

# Ports to expose on workspace startup
ports:
  - port: 6789
    onOpen: open-preview
    name: n8n
    description: n8n
